/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: f18aca39756dbf8073473d7b6542363d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "SlackMCP";
	}
	interface Env {
		SlackMCP: DurableObjectNamespace<import("./src/server").SlackMCP>;
	}
}
interface Env extends Cloudflare.Env {}
